### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by tt-kkaiser** [oscgu/cig#1] opened 2024-06-11 05:48 UTC
When trying to commit into a folder that isnt an git repository the program just segfaults

**Comment by tt-kkaiser** [comment] 2024-06-11 05:54
The program also segfaults when trying to commit without description of your change

**Comment by oscgu** [comment] 2024-06-20 22:48
Should be fixed by now, since I'm not able to reproduce the issue (neither on wsl ubuntu nor arch)

**Closed as completed by oscgu** 2024-06-20 22:48 UTC

**Comment by oscgu** [comment] 2024-07-16 18:52
Actually got fixed in [973ec58](https://github.com/oscgu/cig/commit/973ec5874a04b2c71fa5282f753253df0cb1f649)
